apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: deis/helloworld
        ports:
        - containerPort: 80
          name: http-server
